{% set version = '2.9.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bart
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BART_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BART/BART_{{ version }}.tar.gz
  sha256: 6e23eac476e894c0e6540eaa80e8436ea04261ce6aaac8d4f6f8f7ceeb082e0f

build:
  merge_build_host: True  # [win]
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  host:
    - r-base
    - r-rcpp >=0.12.3
    - r-nlme
    - r-nnet
    - r-survival
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.3
    - r-nlme
    - r-nnet
    - r-survival

test:
  commands:
    - $R -e "library('BART')"           # [not win]
    - "\"%R%\" -e \"library('BART')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=BART
  license: GPL-2.0-or-later
  summary: Bayesian Additive Regression Trees (BART) provide flexible nonparametric modeling
    of covariates for continuous, binary, categorical and time-to-event outcomes.  For
    more information see Sparapani, Spanbauer and McCulloch <doi:10.18637/jss.v097.i01>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - Gattocrucco

# Package: BART
# Type: Package
# Title: Bayesian Additive Regression Trees
# Version: 2.9.6
# Date: 2024-01-09
# Authors@R: c(person('Robert', 'McCulloch', role='aut'), person('Rodney', 'Sparapani', role=c('aut', 'cre'), email='rsparapa@mcw.edu'), person('Robert', 'Gramacy', role='ctb'), person('Matthew', 'Pratola', role='ctb'), person('Charles', 'Spanbauer', role='ctb'), person('Martyn', 'Plummer', role='ctb'), person('Nicky', 'Best', role='ctb'), person('Kate', 'Cowles', role='ctb'), person('Karen', 'Vines', role='ctb'))
# Author: Robert McCulloch [aut], Rodney Sparapani [aut, cre], Robert Gramacy [ctb], Matthew Pratola [ctb], Charles Spanbauer [ctb], Martyn Plummer [ctb], Nicky Best [ctb], Kate Cowles [ctb], Karen Vines [ctb]
# Maintainer: Rodney Sparapani <rsparapa@mcw.edu>
# Description: Bayesian Additive Regression Trees (BART) provide flexible nonparametric modeling of covariates for continuous, binary, categorical and time-to-event outcomes.  For more information see Sparapani, Spanbauer and McCulloch <doi:10.18637/jss.v097.i01>.
# License: GPL (>= 2)
# Depends: R (>= 3.6), nlme, nnet, survival
# Imports: Rcpp (>= 0.12.3), parallel, tools
# LinkingTo: Rcpp
# Suggests: MASS, knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2024-01-09 17:57:57 UTC; rsparapa
# Repository: CRAN
# Date/Publication: 2024-01-09 23:43:08 UTC
